version: '3'

services:
    goskel:
        build: .
        image: ghcr.io/basilboli/goskel
        hostname: "goskel"
        restart: always
        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"
        ports:
            - "3000:8080"
        environment:
            - MONGO_URI=mongodb://mongo-ci-test:27017/goskel-test
            - ADMIN_TOKEN=somesecrettoken
            - MODE=local
            - DB_NAME=goskel-test
        depends_on:
            - mongo-ci-test
            - sftp
        networks:
            - goskel-net

    mongo-ci-test:
        image: mongo:3.4
        ports:
            - "27017:27017"
        hostname: mongo-ci-test
        container_name: mongo-ci-test
        environment:
            SECRET: secret
        restart: on-failure
        networks:
            - goskel-net

    mongo_seed:
        image: mongo:3.4
        links:
            - mongo-ci-test
        volumes:
            - ./mongo-seed:/mongo-seed
        command: ["./mongo-seed/wait-for-it.sh", "mongo-ci-test:27017", "--", "/mongo-seed/import.sh"]
        networks:
            - goskel-net

    sftp:
        image: atmoz/sftp
        hostname: sftp
        container_name: sftp
        ports:
        - "22:22"
        volumes:
            - ./host/upload:/home/foo/upload
            - ./test/ssh/id_rsa.pub:/home/foo/.ssh/keys/id_rsa.pub:ro
        command: foo::1001
        networks:
            - goskel-net
networks:
    goskel-net:
        driver: bridge
